### ISSUE TITLE
createRoute内からmicroCMSのAPIを実行するとエラーになる

### ISSUE THREAD

**Issue by mugi-tech** [mugi-tech/honox-blog-template#1]
## 概要
createRoute内からmicoroCMSのAPIを実行したところ、エラーになっている。
rootには、.envファイルを配置しているので、`serviceDomain`や`api_key`の不備ではなさそう？

create honoでCloudflare pagesやworkersを選び、honoインスタンスを使用して、microCMSのAPIを実行した際は、上手くいっている。
二つの環境差分としたら、buildでvite を使用しているかどうかくらい。
成功している方はvite を使用していないので、それが原因か？
関係があるかどうか分からないが、、
以下、エラー内容。
```
22:34:07 [vite] Error when evaluating SSR module /node_modules/qs/lib/index.js:
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/katoudaiki/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Error when evaluating SSR module /node_modules/microcms-js-sdk/dist/esm/microcms-js-sdk.js: failed to import "/node_modules/qs/lib/index.js"
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/katoudaiki/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Error when evaluating SSR module /app/routes/index.tsx: failed to import "/node_modules/microcms-js-sdk/dist/esm/microcms-js-sdk.js"
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Error when evaluating SSR module /node_modules/honox/dist/server/server.js: failed to import "/app/routes/index.tsx"
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Error when evaluating SSR module /node_modules/honox/dist/server/index.js: failed to import "/node_modules/honox/dist/server/server.js"
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Error when evaluating SSR module /Users/XXXXXX/projects/hono-blog-template/app/server.ts: failed to import "/node_modules/honox/dist/server/index.js"
|- ReferenceError: require is not defined
    at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
    at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)

22:34:07 [vite] Internal server error: require is not defined
      at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
      at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15)
22:34:07 [vite] Internal server error: require is not defined
      at eval (/Users/XXXXXX/projects/hono-blog-template/node_modules/qs/lib/index.js:5:17)
      at instantiateModule (file:///Users/XXXXXX/projects/hono-blog-template/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:15) (x2)
```
以下、該当ソース
```javascript
export const GET = createRoute(async (c) => {
  const client = createClient({
    serviceDomain: c.env.MICROCMS_SERVICE_DOMAIN,
    apiKey: c.env.MICROCMS_API_KEY,
  });
  const categories = await client.getList<Category>({ endpoint: 'categories' });
  console.log(categories.contents);
  return c.render(<div>hello!</div>);
});
```
### 試した事
* `bun run dev`を実行

**Comment by yusukebe** [comment]
@mugi-tech 

こんにちわ。以下のように `ssr.external` を追加するとどうなります？

```ts
import pages from '@hono/vite-cloudflare-pages'
import devServer from '@hono/vite-dev-server'
import honox from 'honox/vite'
import client from 'honox/vite/client'
import { defineConfig } from 'vite'

const entry = './app/server.ts'

export default defineConfig(({ mode }) => {
  if (mode === 'client') {
    return {
      plugins: [client()],
      build: {
        rollupOptions: {
          input: ['/app/style.css'],
          output: {
            assetFileNames: 'static/assets/[name].[ext]'
          }
        }
      }
    }
  } else {
    return {
      // 以下を追加
      ssr: {
        external: ['qs', 'cross-fetch', 'async-retry', 'microcms-js-sdk']
      },
      plugins: [honox(), devServer({ entry }), pages()]
    }
  }
})
```

**Comment by mugi-tech** [comment]
@yusukebe 
お返事が遅れて申し訳ございません。
上記のように`ssr.external`で定義すれば問題なく動作しました！
ご回答いただきありがとうございました！
